import type { Metadata } from 'next'
// styles 
import '@/styles/globals/globalStyles.scss';
// font 
import { marckScriptFont, ptRootVariableFont } from '@/fonts/fonts';
// components
import ContextWrapper from '@/components/rootLayout/ContextWrapper';
import Header from '@/components/rootLayout/Header';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {

	return (
		<html lang="ru" className={`${marckScriptFont.variable} ${ptRootVariableFont.variable}`}>
			<ContextWrapper>
				<Header />
				{children}
			</ContextWrapper>
		</html>
	)
}