import type { Metadata } from 'next'
// styles 
import '@/styles/globals/globalStyles.scss';
// font 
import { marckScriptFont, ptRootBoldFont, ptRootRegularFont } from '@/fonts/fonts';
// components
import ContextWrapper from '@/components/rootLayout/ContextWrapper';
import Body from '@/components/rootLayout/Body';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {

	return (
		<html lang="ru" className={`${marckScriptFont.variable} ${ptRootBoldFont.variable} ${ptRootRegularFont.variable}`}>
			<ContextWrapper>
				<Body>
					{children}
				</Body>
			</ContextWrapper>
		</html>
	)
}